// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ApiDB.dal.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ApiDB
{
    public partial class School21 : IEntityBase
    {

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string CampusName { get; set; }
        public List<User> Users { get; set; }
        public List<Subject> Subjects { get; set; }


    }
}