// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BotClient
{
    [Serializable]
    public partial class School21
    {

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string CampusName { get; set; }
        public List<User> Users { get; set; }
        public List<Subject> Subjects { get; set; }


    }
}